export const ROLES_KEY = '__ROLES_KEY__'
export const IS_PUBLIC_KEY = '__IS_PUBLIC_KEY__'

export const CACHE_OPENAI_KEYS = 'OPENAI_KEYS'
export const CACHE_BALANCE = 'BALANCE'
export const CACHE_WXPAY = 'WXPAY'
export const CACHE_QRCODE_LOGIN = 'QRCODE_LOGIN'
export const CACHE_MAIL_CODE = 'MAIL_CODE'
export const CACHE_USER = 'USER'
export const CACHE_ADMIN = 'ADMIN'
export const CACHE_MESSAGE = 'MESSAGE'
