export const WHERE_OPTION_METADATA = 'WHERE_OPTION_METADATA'
export const WHERE_OPTION_TYPE_METADATA = 'WHERE_OPTION_TYPE_METADATA'
export const WHERE_OPTION_NAME_METADATA = 'WHERE_OPTION_NAME_METADATA'
export const WHERE_OPTION_ENTITY_METADATA = 'WHERE_OPTION_ENTITY_METADATA'
