version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: sso_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: sso
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
  mongo-express:
    image: mongo-express:latest
    container_name: sso_mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    depends_on:
      - mongo
  redis:
    image: redis:7
    container_name: sso_redis
    ports:
     - "6379:6379"
    volumes:
     - redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    privileged: true
    restart: unless-stopped
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: sso_redis_commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:123456,local:redis:6379:1:123456
      - PORT=8082
    ports:
      - 8082:8082
    depends_on:
      - redis
volumes:
    mongo:
    redis:
