version: '3.8'

services:
  postgres:
    container_name: sso_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sso
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  pgadmin:
    container_name: sso_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sso.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 5050:8081
    depends_on:
      - postgres
    restart: unless-stopped


  redis:
    image: redis:7
    container_name: sso_redis
    ports:
     - "6379:6379"
    volumes:
     - redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    privileged: true
    restart: unless-stopped


  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: sso_redis_commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:123456,local:redis:6379:1:123456
      - PORT=8082
    ports:
      - 8082:8082
    depends_on:
      - redis

volumes:
    postgres:
    redis:
